[package]
name = "pyo3_special_method_derive_0_21"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
once_cell = "1.17"
pyo3.workspace = true
pyo3_special_method_derive_macro_0_21.workspace = true
